import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Known debt: ~150 `any` casts on Supabase query results predate the
      // generated types. Downgraded to warn so CI blocks on real problems;
      // remove this line once the typing refactor lands.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    // Plain-Node tooling scripts (migration applier, setup.sql builder) are
    // CommonJS by design — require() is correct there.
    files: ["scripts/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Supabase CLI local-dev scratch (generated by `supabase start`):
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
